<?php

namespace App\Http\Controllers;

use App\Company;
use App\Http\Requests\CompanyRequestForm;
use App\Role;
use Illuminate\Http\Request;

class InmobiliariaController extends CompanyController
{

    public function index(Request $request,$tipo_company = 'inmobiliaria',$vista = 'crm.inmobiliaria.list')
    {
        return parent::index($request,$tipo_company,$vista); // TODO: Change the autogenerated stub
    }


    public function create($company_type = 'inmobiliaria',$vista = 'crm.inmobiliaria.create')
    {
        return parent::create($company_type ,$vista); // TODO: Change the autogenerated stub
    }


    public function edit(Company $company,$vista = 'crm.inmobiliaria.edit')
    {
        return parent::edit($company, $vista = 'crm.inmobiliaria.edit'); // TODO: Change the autogenerated stub
    }

    public function show(Company $company, $vista = 'crm.inmobiliaria.show')
    {
        return parent::show($company, $vista = 'crm.inmobiliaria.show'); // TODO: Change the autogenerated stub
    }


}
