<?php

namespace App\Http\Controllers;

use App\Http\Requests\PropiedadRequestForm;
use App\Municipio;
use App\Propiedades;
use App\Provincia;
use App\Sector;
use App\TiposPropiedades;

class PropiedadesController extends InmuebleController
{

    public function index($clase_inmueble = 'propiedad', $vista = null)
    {

        return parent::index($clase_inmueble = 'propiedad',  $vista = 'crm.propiedades.list'); // TODO: Change the autogenerated stub
    }

    public function create($clase_inmueble = null, $vista = null)
    {
        return parent::create($clase_inmueble = 'propiedad', $vista = 'crm.propiedades.create'); // TODO: Change the autogenerated stub
    }


    public function edit(Propiedades $propiedades, $vista = '')
    {
        return parent::edit($propiedades, $vista = 'crm.propiedades.edit'); // TODO: Change the autogenerated stub
    }



}
