<?php

namespace App\Http\Controllers;

use App\Http\Requests\PropiedadRequestForm;
use Illuminate\Http\Request;

class ProyectosController extends InmuebleController
{



    public function index($clase_inmueble = 'proyectos', $vista = null)
    {

        return parent::index($clase_inmueble = 'proyecto',  $vista = 'crm.proyectos.list'); // TODO: Change the autogenerated stub
    }

    public function create($clase_inmueble = null, $vista = null)
    {
        return parent::create($clase_inmueble = 'proyecto', $vista = 'crm.proyectos.create'); // TODO: Change the autogenerated stub
    }


}
